---
- name: Create tls location
  when: bareos_tls_path is defined
  ansible.builtin.file: 
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_tls_path }}"

- name: Copy Bareos Director configuration file
  ansible.builtin.template:
    src: director.conf.j2
    dest: /etc/bareos/bareos-dir.d/director/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.director }}"
  notify:
    - Restart bareos-dir service

- name: Find unmanaged director configurations
  ansible.builtin.find:
    paths: /etc/bareos/bareos-dir.d/director
    file_type: file
    excludes: "{{ bareos_dir.director | map(attribute='name') | product(['.conf']) | map('join') | flatten }}"
  register: fdirout

- name: Remove unmanaged director configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ fdirout.files | map(attribute='path') | unique }}"
  notify:
    - Restart bareos-dir service

- name: Copy Bareos bconsole configuration file
  ansible.builtin.template:
    src: bconsole.conf.j2
    dest: /etc/bareos/bconsole.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.bconsole }}"
  notify:
    - Restart bareos-dir service

- name: Copy Bareos catalog configuration for PostgreSQL
  ansible.builtin.template:
    src: catalog.conf.j2
    dest: /etc/bareos/bareos-dir.d/catalog/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.catalog }}"
  notify:
    - Restart bareos-dir service

- name: Enable packages gather facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set password for Bareos Database user with sudo packages (skip if sudo isn't installed)
  when: "'sudo' in ansible_facts.packages"
  # no_log: true
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_user: 
    db: bareos
    name: bareos
    password: "{{ item.password | mandatory }}"
  with_items: "{{ bareos_dir.catalog }}"
  notify:
    - Restart postgresql service

- name: Grant privileges to tables for Bareos DB user
  become: true
  become_method: su
  become_user: postgres
  ansible.builtin.command: sh /usr/lib/bareos/scripts/grant_bareos_privileges
  changed_when: false
