---
- name: Configure bareos-dir fileset
  no_log: true
  ansible.builtin.template:
    src: fileset.conf.j2
    dest: /etc/bareos/bareos-dir.d/fileset/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.fileset }}"
  notify:
    - restart bareos-dir service
