---
- name: Update repo cache and install a few prerequisite packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: true

- name: Add official Bareos package authentication key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E01957D6C9FED482
    state: present

- name: Add the Bareos repository to APT sources
  template:
    src: bareos.list.j2
    dest: /etc/apt/sources.list.d/bareos.list
    mode: '0644'

- name: Install Bareos Director Daemon
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - bareos-database-postgresql
    - bareos-director
    - bareos-bconsole
  notify:
    - enable bareos-dir service
    - restart bareos-dir service
