---
- name: Configure bareos-dir jobdefs
  template:
    src: jobdefs.conf.j2
    dest: /etc/bareos/bareos-dir.d/jobdefs/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.jobdefs }}"
  notify:
    - reload bareos-dir service
