---
- name: Include ./install.yml
  ansible.builtin.import_tasks: install.yml
  tags:
    - install_bareos_dir
    - install

- name: Include ./configure.yml
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure_bareos_dir
    - configure

- name: Include ./webui.yml
  when: bareos_dir.webui is defined
  ansible.builtin.import_tasks: webui.yml
  tags:
    - configure_bareos_webui
    - bareos_webui_console
    - bareos_webui

- name: Include ./storage.yml
  when: bareos_dir.storage is defined
  ansible.builtin.import_tasks: storage.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_storage
    - bareos_dir

- name: Include ./pool.yml
  when: bareos_dir.pool is defined
  ansible.builtin.import_tasks: pool.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_pool
    - bareos_dir

- name: Include ./fileset.yml
  when: bareos_dir.fileset is defined
  ansible.builtin.import_tasks: fileset.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_fileset
    - bareos_dir

- name: Include ./schedule.yml
  when: bareos_dir.schedule is defined
  ansible.builtin.import_tasks: schedule.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_schedule
    - bareos_dir

- name: Include ./jobdefs.yml
  when: bareos_dir.jobdefs is defined
  ansible.builtin.import_tasks: jobdefs.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_jobdefs
    - bareos_dir

- name: Include ./client.yml
  when: bareos_dir.client is defined
  ansible.builtin.import_tasks: client.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_client
    - bareos_dir

- name: Include ./job.yml
  when: bareos_dir.job is defined
  ansible.builtin.import_tasks: job.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_job
    - bareos_dir

- name: Include ./messages.yml
  when: bareos_dir.messages is defined
  ansible.builtin.import_tasks: messages.yml
  tags:
    - configure_bareos_dir
    - bareos_dir_messages
    - bareos_dir

# - name: Include ./openssl.yml
#   when: bareos_dir.openssl is defined
#   ansible.builtin.import_tasks: openssl.yml
#   tags:
#     - configure_bareos_dir
#     - bareos_dir_openssl
#     - bareos_dir

# - name: Include ./hachicorp.yml
#   when: bareos_dir.hashicorp_vault is defined
#   ansible.builtin.import_tasks: hashicorp.yml
#   tags:
#     - configure_bareos_dir
#     - bareos_dir_hashicorp
#     - bareos_dir
