---
- import_tasks: install.yml
  tags:
    - install_bareos_dir
    - install

- import_tasks: configure.yml
  tags:
    - configure_bareos_dir
    - configure

- import_tasks: webui.yml
  when: bareos_dir.webui is defined
  tags:
    - configure_bareos_webui
    - bareos_webui_console
    - bareos_webui

- import_tasks: storage.yml
  when: bareos_dir.storage is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_storage
    - bareos_dir

- import_tasks: pool.yml
  when: bareos_dir.pool is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_pool
    - bareos_dir

- import_tasks: fileset.yml
  when: bareos_dir.fileset is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_fileset
    - bareos_dir

- import_tasks: schedule.yml
  when: bareos_dir.schedule is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_schedule
    - bareos_dir

- import_tasks: jobdefs.yml
  when: bareos_dir.jobdefs is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_jobdefs
    - bareos_dir

- import_tasks: client.yml
  when: bareos_dir.client is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_client
    - bareos_dir

- import_tasks: job.yml
  when: bareos_dir.job is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_job
    - bareos_dir

- import_tasks: messages.yml
  when: bareos_dir.messages is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_messages
    - bareos_dir

- import_tasks: openssl.yml
  when: bareos_dir.openssl is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_openssl
    - bareos_dir

- import_tasks: hashicorp.yml
  when: bareos_dir.hashicorp_vault is defined
  tags:
    - configure_bareos_dir
    - bareos_dir_hashicorp
    - bareos_dir
