---
- name: Configure bareos-dir messages
  ansible.builtin.template:
    src: messages.conf.j2
    dest: /etc/bareos/bareos-dir.d/messages/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.messages }}"
  notify:
    - restart bareos-dir service
