---
- name: Install/Update OpenSSL
  apt:
    update_cache: true
    name: openssl
    state: present

- name: Create directory for certificates
  no_log: true
  file: 
    path: "{{ bareos_dir.tls_path }}/certs"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos

- name: Create directory for csr
  no_log: true
  file: 
    path: "{{ bareos_dir.tls_path }}/csr"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos

- name: Create directory for private keys
  no_log: true
  file: 
    path: "{{ bareos_dir.tls_path }}/private"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos

- name: Copy openssl.cnf to openssl directory for Bareos
  template:
    src: openssl.cnf.j2
    dest: "{{ bareos_dir.tls_path }}/openssl.cnf"
    mode: '0644'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.openssl }}"
  environment:
    OPENSSL_CONF: "/etc/bareos/tls/openssl.cnf"

- name: Add serial file for openssl
  lineinfile:
    path: "{{ bareos_dir.tls_path }}/serial"
    mode: '0644'
    line: 01
    create: true

- name: Add index.txt file for openssl
  file:
    dest: "{{ bareos_dir.tls_path }}/index.txt"
    state: touch
    mode: '0644'
    owner: root
    group: root
    modification_time: preserve
    access_time: preserve

- name: Generate private key for CA
  openssl_privatekey:
    path: "{{ bareos_dir.tls_path }}/CA.key"
    size: 4096
    state: present

- name: Generate csr for CA
  openssl_csr:
    path: "{{ bareos_dir.tls_path }}/CA.csr"
    privatekey_path: "{{ bareos_dir.tls_path }}/CA.key"
    common_name: "{{ ansible_nodename }}"
    state: present

- name: Generate CA certificate
  openssl_certificate:
    provider: selfsigned
    path: "{{ bareos_dir.tls_path }}/CA.crt"
    privatekey_path: "{{ bareos_dir.tls_path }}/CA.key"
    csr_path: "{{ bareos_dir.tls_path }}/CA.csr"
    state: present

- name: Generate private key's for clients
  openssl_privatekey:
    path: "{{ bareos_dir.tls_path }}/private/{{ item.name }}.key"
    size: 4096
    state: present
  loop: "{{ bareos_dir.tls_clients }}"

- name: Generate csr's for clients
  openssl_csr:
    path: "{{ bareos_dir.tls_path }}/csr/{{ item.name }}.csr"
    privatekey_path: "{{ bareos_dir.tls_path }}/private/{{ item.name }}.key"
    common_name: "{{ item.name }}"
    state: present
  loop: "{{ bareos_dir.tls_clients }}"

- name: Generate clients certificate's
  openssl_certificate:
    provider: ownca
    path: "{{ bareos_dir.tls_path }}/certs/{{ item.name }}.crt"
    csr_path: "{{ bareos_dir.tls_path }}/csr/{{ item.name }}.csr"
    ownca_path: "{{ bareos_dir.tls_path }}/CA.crt"
    ownca_privatekey_path: "{{ bareos_dir.tls_path }}/CA.key"
    state: present
  loop: "{{ bareos_dir.tls_clients }}"
