---
- name: Install/Update OpenSSL
  apt:
    update_cache: true
    name: openssl
    state: present

- name: Create directory for certificates
  no_log: true
  file: 
    path: "{{ item.path }}/certs"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.openssl }}"

- name: Create directory for csr
  file: 
    path: "{{ item.path }}/csr"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.openssl }}"

- name: Create directory for private keys
  file: 
    path: "{{ item.path }}/private"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.openssl }}"

- name: Copy openssl.cnf to {{ item.path }}
  template:
    src: openssl.cnf.j2
    dest: "{{ item.path }}/openssl.cnf"
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.openssl }}"
