---
- name: Configure bareos-dir pool
  template:
    src: pool.conf.j2
    dest: /etc/bareos/bareos-dir.d/pool/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.pool }}"
  notify:
    - reload bareos-dir service
