---
- name: Configure bareos-dir schedule
  ansible.builtin.template:
    src: schedule.conf.j2
    dest: /etc/bareos/bareos-dir.d/schedule/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_dir.schedule }}"
  notify:
    - Restart bareos-dir service
