---
- name: enable bareos-dir service
  ansible.builtin.service:
    name: bareos-dir
    enabled: true

- name: restart bareos-dir service
  ansible.builtin.service:
    name: bareos-dir
    state: restarted

- name: restart postgresql service
  ansible.builtin.service:
    name: postgresql
    state: restarted
