---
- name: Converge
  hosts: all
  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: true
    - name: "Dependency role for PostgreSQL Server"
      ansible.builtin.include_role:
        name: "leadlineit.postgresql"
    - name: "Include leadlineit.bareos_dir"
      ansible.builtin.include_role:
        name: "leadlineit.bareos_dir"
